### PR TITLE
Menu loop error handled(server side) and masking of password(server side)

### PR DESCRIPTION
**Pull request by pritindra**
Error handling and masking password.

### CODE REVIEW

**Comment by Dsantra92** [comment]
@pritindra It is a common practice to  name of the PR based on the particular issue that the pr solves. This helps better tracking of the development of the project. Same applies for the commits you make on the branch.

**Comment by pritindra** [comment]
So sorry about that. I will do as you said. Should a open a new PR?

**Comment by Dsantra92** [comment]
> So sorry about that. I will do as you said. Should a open a new PR?

You will be able to change the name of the PR, no need to make a separate pr.

**Comment by pritindra** [comment]
Is it okay now?

**Comment by Dsantra92** [comment]
Congrats on your first commit. 💙

**Pull request merged**
